
import __ASTRO_IMAGE_IMPORT_Z26coFo from "../../../assets/blog/animations-in-astro-rocket.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fanimations-in-astro-rocket.mdx";
import __ASTRO_IMAGE_IMPORT_Z2rrCD4 from "../../../assets/blog/astro-rocket-configuration-guide.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fastro-rocket-configuration-guide.mdx";
import __ASTRO_IMAGE_IMPORT_mjV45 from "../../../assets/blog/astro-rocket-getting-started.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fastro-rocket-getting-started.mdx";
import __ASTRO_IMAGE_IMPORT_2oAtR3 from "../../../assets/blog/colour-mode-system.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fcolour-mode-system.mdx";
import __ASTRO_IMAGE_IMPORT_1qnQU7 from "../../../assets/blog/component-library.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fcomponent-library.mdx";
import __ASTRO_IMAGE_IMPORT_Z1I4cm4 from "../../../assets/blog/contact-form-resend-setup.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fcontact-form-resend-setup.mdx";
import __ASTRO_IMAGE_IMPORT_2js4sS from "../../../assets/blog/design-system-color-tokens.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fdesign-system-color-tokens.mdx";
import __ASTRO_IMAGE_IMPORT_APffu from "../../../assets/blog/hero-scroll-indicator.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fhero-scroll-indicator.mdx";
import __ASTRO_IMAGE_IMPORT_Z1VTDyL from "../../../assets/blog/hero-typing-effect.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fhero-typing-effect.mdx";
import __ASTRO_IMAGE_IMPORT_SguHG from "../../../assets/blog/scroll-progress-bar.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fscroll-progress-bar.mdx";
import __ASTRO_IMAGE_IMPORT_Z3ypL0 from "../../../assets/blog/scroll-progress-ring.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fscroll-progress-ring.mdx";
import __ASTRO_IMAGE_IMPORT_ZflPH3 from "../../../assets/blog/seo-in-astro-rocket.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fseo-in-astro-rocket.mdx";
import __ASTRO_IMAGE_IMPORT_jqEmu from "../../assets/projects/astro-rocket-dark.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fastro-rocket.mdx";
export default new Map([["../../../assets/blog/animations-in-astro-rocket.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fanimations-in-astro-rocket.mdx", __ASTRO_IMAGE_IMPORT_Z26coFo], ["../../../assets/blog/astro-rocket-configuration-guide.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fastro-rocket-configuration-guide.mdx", __ASTRO_IMAGE_IMPORT_Z2rrCD4], ["../../../assets/blog/astro-rocket-getting-started.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fastro-rocket-getting-started.mdx", __ASTRO_IMAGE_IMPORT_mjV45], ["../../../assets/blog/colour-mode-system.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fcolour-mode-system.mdx", __ASTRO_IMAGE_IMPORT_2oAtR3], ["../../../assets/blog/component-library.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fcomponent-library.mdx", __ASTRO_IMAGE_IMPORT_1qnQU7], ["../../../assets/blog/contact-form-resend-setup.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fcontact-form-resend-setup.mdx", __ASTRO_IMAGE_IMPORT_Z1I4cm4], ["../../../assets/blog/design-system-color-tokens.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fdesign-system-color-tokens.mdx", __ASTRO_IMAGE_IMPORT_2js4sS], ["../../../assets/blog/hero-scroll-indicator.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fhero-scroll-indicator.mdx", __ASTRO_IMAGE_IMPORT_APffu], ["../../../assets/blog/hero-typing-effect.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fhero-typing-effect.mdx", __ASTRO_IMAGE_IMPORT_Z1VTDyL], ["../../../assets/blog/scroll-progress-bar.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fscroll-progress-bar.mdx", __ASTRO_IMAGE_IMPORT_SguHG], ["../../../assets/blog/scroll-progress-ring.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fscroll-progress-ring.mdx", __ASTRO_IMAGE_IMPORT_Z3ypL0], ["../../../assets/blog/seo-in-astro-rocket.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fen%2Fseo-in-astro-rocket.mdx", __ASTRO_IMAGE_IMPORT_ZflPH3], ["../../assets/projects/astro-rocket-dark.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fastro-rocket.mdx", __ASTRO_IMAGE_IMPORT_jqEmu]]);
		